menu:
  Home: /
  Archives: archives
  pages:
    About: about

widgets:
- tag
#- recent_posts

excerpt_link: Continue →

mathjax: true
fancybox: true
disqus_shortname: physbar

social:
  twitter: false
  github: true
  gplus: true
  rss: true

rss: /atom.xml

twitter:
  username:

github:
  username: PhysBar

gplus:
  username: 

addit:
  facebook: false
  twitter: false
  gplus: false
  pinit: false
  publid: