menu:
  通知|Notice: /notice
  存档|Archives: /archives
  关于|About: /about

widgets:
- search
- category
- recent_posts
- tag

excerpt_link: Read More
archive_yearly: false #按年存档

twitter:
  username:
  show_replies: false
  tweet_count: 5

duoshuo_shortname: XY

# turn off social sharing
addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss: /atom.xml

comment_provider:
# # Facebook comment
# facebook:
#   appid: 123456789012345
#   comment_count: 5
#   comment_width: 840
#   comment_colorscheme: light